version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant:v1.13.4
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO  # ログレベルを設定
      - QDRANT__STORAGE__DISK_CACHE_SIZE=128  # ディスクキャッシュのサイズ（MB）

volumes:
  qdrant_data:
    driver: local
